spring:
  application:
    name: movies-api
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    initializationMode: NEVER
    hikari:
      maximum-pool-size: 10
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      org.hibernate.envers.default_schema: movies
      order_inserts: true
      order_updates: true
      jdbc:
        batch_size: 30
  liquibase:
    change-log: classpath:/db/master.xml
  jackson:
    deserialization:
      accept_empty_string_as_null_object: true
      fail-on-ignored-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
  h2:
    console:
      enabled: false
  zipkin:
    enabled: false

server:
  port: 8082
logging:
  level:
    br.com.elotech.saude: DEBUG
management:
  health:
    db:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
